apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  labels:
    app.kubernetes.io/name: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: secret/Dev-secret/authentik
        property: secret-key

    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: secret/Dev-secret/authentik
        property: email-password

    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: secret/Dev-secret/authentik
        property: pg-password

